### ISSUE TITLE
I want limit number of post and "see all" funzionality

### ISSUE THREAD

**Issue by GabrieleSammartino** [bowlhat/wp-a-z-listing#23]
I want limit number of post and "see all" funzionality

**Comment by GabrieleSammartino** [comment]
Example :  
https://imgur.com/a/9YaxM

**Comment by diddledan** [comment]
You can do this yourself with a custom template. All you need to do is break the item loop when your desired number of items is displayed to back out into the letter loop for the next letter.

example, probably non-functional, pseudocode to provide inspiration - use the template(s) included in the plugin folder for the base of your new template with modifications to break at your desired number of items:

```php
<?php
while ( $q_z_query->have_letters() ) :
    $a_z_query->the_letter();
    if ( $a_z_query->have_items() ) :
        ?>
        <h2><?php $a_z_query->the_letter_title(); ?></h2>
        <?php
        $item_count = 1;
        while( $a_z_query->have_items() ) :
            if ( $item_count++ >= 10 ) :
                ?><a href="more link here">MORE!</a><?php // send the user to...
                break; // break when we reach 10 items shown
            endif;
            $a_z_query->the_item();
            ?>
            <a href="<?php $a_z_query->the_permalink(); ?>"><?php $a_z_query->the_title(); ?></a>
            <?php
        endwhile;
    endif;
endwhile;
```

This only works if you have another page somewhere displaying the posts you want to keep hidden from your a-z listing. If you want the "more" items to magically appear when the user clicks the mythical "more" link then you'll need some javascript instead of the above php template to hide the excess items on page load and reveal them when the user clicks the link.
